# Generated by Django 2.2.1 on 2019-06-18 03:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('idincident', models.AutoField(primary_key=True, serialize=False)),
                ('kasus', models.TextField()),
                ('applikasi', models.CharField(default='-', max_length=45)),
                ('solusi', models.TextField()),
                ('createdby', models.CharField(max_length=20)),
                ('lastupdate', models.CharField(default=datetime.datetime.now, max_length=30)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('busscd', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('like', models.BooleanField(default=0)),
                ('dislike', models.BooleanField(default=0)),
                ('hits', models.BooleanField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc_wiki.Incident')),
            ],
        ),
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('isi_komentar', models.TextField()),
                ('tanggal_komentar', models.DateTimeField(default=datetime.datetime.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hc_wiki.Incident')),
            ],
        ),
    ]
