# Generated by Django 2.2.1 on 2019-06-13 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki-admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
