# Generated by Django 2.2.1 on 2019-05-31 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('idincident', models.AutoField(primary_key=True, serialize=False)),
                ('kasus', models.TextField()),
                ('applikasi', models.CharField(max_length=45)),
                ('solusi', models.TextField()),
                ('createdby', models.CharField(max_length=20)),
                ('lastupdate', models.CharField(max_length=30)),
                ('like', models.IntegerField()),
                ('dislike', models.IntegerField()),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_wiki.Incident')),
            ],
        ),
    ]
