# Generated by Django 2.2.1 on 2019-05-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Konten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('isi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('nik', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('noHp', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
