# Generated by Django 2.2.1 on 2019-05-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='konten',
            name='highlight',
            field=models.TextField(default='cek'),
            preserve_default=False,
        ),
    ]
