# Generated by Django 2.2.1 on 2019-05-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konten',
            name='id',
        ),
        migrations.AddField(
            model_name='konten',
            name='idkonten',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
