# Generated by Django 2.2.1 on 2019-05-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='like',
        ),
        migrations.AddField(
            model_name='incident',
            name='direktori',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='flagaktif',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='flagapprove',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='flagdefinisi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
