# Generated by Django 2.2.1 on 2019-06-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='applikasi',
            field=models.CharField(default='-', max_length=45),
        ),
        migrations.AlterField(
            model_name='incident',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
