# Generated by Django 2.2.1 on 2019-05-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0002_konten_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('idincident', models.AutoField(primary_key=True, serialize=False)),
                ('kasus', models.TextField()),
                ('applikasi', models.CharField(max_length=45)),
                ('solusi', models.TextField()),
                ('createdby', models.CharField(max_length=20)),
                ('lastupdate', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=200)),
                ('direktori', models.CharField(max_length=500)),
                ('flagdefinisi', models.IntegerField(blank=True, null=True)),
                ('flagaktif', models.IntegerField(blank=True, null=True)),
                ('flagapprove', models.IntegerField(blank=True, null=True)),
                ('hits', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
