# Generated by Django 2.2.1 on 2019-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0002_auto_20190531_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='direktori',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='flagaktif',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='flagapprove',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='flagdefinisi',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='link',
        ),
        migrations.AddField(
            model_name='incident',
            name='dislike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
