# Generated by Django 2.2.1 on 2019-05-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0002_konten_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konten',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
