# Generated by Django 2.2.1 on 2019-06-13 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0002_auto_20190613_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='incident',
            name='lastupdate',
            field=models.CharField(default=datetime.datetime.now, max_length=30),
        ),
    ]
