# Generated by Django 2.2.1 on 2019-05-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0003_auto_20190529_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='konten',
            old_name='id',
            new_name='idincident',
        ),
    ]
