# Generated by Django 2.2.1 on 2019-06-04 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0003_auto_20190531_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('isi_komentar', models.TextField()),
                ('tanggal_komentar', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='dislike',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='hits',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='log',
            name='like',
            field=models.BooleanField(default=0),
        ),
    ]
