# Generated by Django 2.2.1 on 2019-06-04 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0004_auto_20190604_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Komentar',
        ),
    ]
