# Generated by Django 2.2.1 on 2019-06-04 10:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_wiki', '0005_delete_komentar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id_komentar', models.AutoField(primary_key=True, serialize=False)),
                ('nik', models.IntegerField()),
                ('isi_komentar', models.TextField()),
                ('tanggal_komentar', models.DateTimeField(default=datetime.datetime.now)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_wiki.Incident')),
            ],
        ),
    ]
